server:
  port: 8080
spring:
  application:
    name: gs-spring-boot-kafka-producer-v3
  main:
    banner-mode: "off"
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
    consumer:
      key-deserializer:  org.apache.kafka.common.serialization.LongDeserializer
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
#    root: warn
    com.ashu.practice: debug